[package]
name = "dioxus-rsx-hotreload"
edition = "2024"
version = "0.7.0-alpha.2"
resolver = "3"
authors = ["Jonathan Kelley", "Evan Almloff"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
description = "CLI Configuration for dioxus-cli"
keywords = ["dom", "ui", "gui", "react"]

[dependencies]
dioxus-rsx = { path = "../rsx" }
internment = "0.8.6"
proc-macro2 = { version = "1.0.101", features = ["span-locations"] }
proc-macro2-diagnostics = "0.10.1"
quote = "1.0.40"
syn = { version = "2.0.106", features = ["full", "extra-traits", "visit", "visit-mut"] }
tracing = "0.1.41"
dioxus-core = { path = "../core" }
dioxus-core-types = { path = "../core-types" }
