# Nightly Rustfmt Configuration for Dioxus
# Enables unstable formatting features for optimal code style

unstable_features = true

# Import organization
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Function formatting
fn_single_line = false
fn_params_layout = "Tall"

# Control flow
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"

# Comments and documentation
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Misc formatting
trailing_comma = "Vertical"
trailing_semicolon = true
use_small_heuristics = "Default"
where_single_line = true

# String formatting
format_strings = true

# Macro formatting
format_macro_matchers = true
format_macro_bodies = true

# Module organization
reorder_modules = true

# Style preferences
edition = "2024"
newline_style = "Unix"
hard_tabs = false
tab_spaces = 4
max_width = 100