[package]
name = "dioxus-playwright-web-test"
version = "0.0.1"
edition = "2024"
description = "Playwright test for Dioxus Web"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
dioxus = { path = "../../dioxus", features = ["web"] }
serde_json = "1.0.145"
tracing = "0.1.41"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.103"
web-sys = { version = "0.3.80", features = ["Element", "Window"] }
