[package]
name = "file-explorer"
edition = "2024"
version = "0.1.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { path = "../../packages/dioxus", features = ["desktop"] }
open = "5.3.2"
