[package]
name = "dioxus-core-macro"
version = "0.7.0-alpha.2"
authors = ["Jonathan Kelley"]
edition = "2024"
resolver = "3"
description = "Core macro for Dioxus Virtual DOM"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = { version = "2.0.106", features = ["full", "extra-traits", "visit"] }
dioxus-rsx = { path = "../rsx" }
convert_case = "0.8.0"

[dev-dependencies]
dioxus = { path = "../dioxus" }
dioxus-html = { path = "../html", features = ["serialize"]}
rustversion = "1.0.22"
tokio = { version = "1.47.1", features = ["full", "time"] }
trybuild = "1.0.111"

[features]
default = []

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
