[package]
name = "dioxus-html"
version = "0.7.0-alpha.2"
authors = ["Jonathan Kelley"]
edition = "2024"
description = "HTML Element pack for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react"]

[dependencies]
dioxus-core = { path = "../core" }
dioxus-core-macro = { path = "../core-macro" }
dioxus-core-types = { path = "../core-types" }
dioxus-rsx = { path = "../rsx", optional = true }
dioxus-html-internal-macro = { path = "../html-internal-macro" }
dioxus-hooks = { path = "../hooks" }
generational-box = { path = "../generational-box" }
serde = { version = "1.0.226", features = ["derive"], optional = true }
serde_repr = { version = "0.1.20", optional = true }
js-sys = { version = "0.3.80", optional = true }
keyboard-types = { version = "0.8.1", default-features = false }
async-trait = "0.1.89"
tokio = { version = "1.47.1", features = ["fs", "io-util"], optional = true }
futures-channel = "0.3.31"
serde_json = { version = "1.0.145", optional = true }
tracing = "0.1.41"
rustversion = "1.0.22"
euclid = "0.22.11"
enumset = "1.1.10"

[build-dependencies]
lazy-js-bundle = { path = "../lazy-js-bundle" }

[dev-dependencies]
serde_json = "1"
dioxus = { path = "../dioxus" }
dioxus-web = { path = "../web" }
tokio = { version = "1.47.1", features = ["time"] }
manganis = { path = "../manganis/manganis" }

[features]
default = ["serialize"]
serialize = [
    "dep:serde",
    "dep:serde_json",
    "dep:serde_repr",
    "euclid/serde",
    "keyboard-types/serde",
    "dioxus-core/serialize"
]
# TODO: Remove the mounted feature flag in the next major release. It no longer activates any extra code
mounted = []
# TODO: Remove the file engine feature flag in the next major release. It no longer activates any extra code
file_engine = []
hot-reload-context = ["dep:dioxus-rsx"]
html-to-rsx = []

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
feature = ["html-to-rsx", "hot-reload-context", "html-to-rsx"]
