[package]
name = "subsecond"
edition = "2024"
version = "0.7.0-alpha.2"
authors = ["Jonathan Kelley"]
description = "A runtime hotpatching engine for Rust hot-reloading."
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
keywords = ["hotpatch", "engine", "subsecond", "dioxus", "hot-reload"]

[dependencies]
serde = { version = "1.0.226", features = ["derive"] }
subsecond-types = { path = "../subsecond-types" }
thiserror = "2.0.16"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.80", features = ["FetchEvent", "Request", "Window", "Response", "ResponseType", "console"] }
wasm-bindgen = "0.2.103"
wasm-bindgen-futures = "0.4.53"
js-sys = "0.3.80"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libloading = "0.8.9"
libc = "1.0.0-alpha.1"
memmap2 = "0.9.8"

[target.'cfg(target_os = "android")'.dependencies]
memfd = "0.6.5"
