[package]
name = "suspense-carousel"
edition = "2024"
version = "0.6.1"
publish = false

[dependencies]
dioxus = { path = "../../dioxus", features = ["fullstack"] }
async-std = "1.13.2"
serde = "1.0.226"

[features]
default = []
server = ["dioxus/server"]
web = ["dioxus/web"]
