[package]
name = "nested-suspense"
version = "0.1.0"
edition = "2024"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { path = "../../dioxus", features = ["fullstack"] }
serde = "1.0.226"
tokio = { version = "1.47.1", features = ["full"] }

[features]
default = []
server = ["dioxus/server"]
web = ["dioxus/web"]

# We need a separate bin for the SSG build to avoid conflicting server caches
[[bin]]
name = "nested-suspense-ssg"
path = "src/ssg.rs"

[[bin]]
name = "nested-suspense"
path = "src/main.rs"
