[package]
name = "dioxus-dx-wire-format"
edition = "2024"
resolver = "3"
version = "0.7.0-alpha.2"
publish = true
authors = ["Jonathan Kelley"]
description = "Wire format for the Dioxus CLI"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com/learn/0.6/"
keywords = ["dom", "ui", "gui", "react", "wasm"]

[dependencies]
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
cargo_metadata = "0.22.0"
