[package]
name = "dioxus-cli-opt"
edition = "2024"
resolver = "3"
version = "0.7.0-alpha.2"
authors = ["Jonathan Kelley", "Evan Almloff"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
description = "CLI optimizations for dioxus-cli"
keywords = ["dom", "ui", "gui", "react"]

[dependencies]
anyhow = "1.0.100"
manganis = { path = "../manganis/manganis" }
manganis-core = { path = "../manganis/manganis-core" }
object = { version = "0.37.3", features = ["wasm"] }
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
const-serialize = { path = "../const-serialize", features = ["serde"] }
tracing = "0.1.41"
rayon = "1.11.0"

# Image compression/conversion
# - JPEG
mozjpeg = { version = "0.10.13", default-features = false, features = [
    "parallel",
] }
# - PNG
imagequant = "4.4.1"
png = "0.18.0"

# Image format/conversion
image = { version = "0.25", features = ["avif"] }

# CSS Minification
lightningcss = { version = "1.0.0-alpha.67", features = [
    "browserslist",
    "into_owned",
] }

# SCSS Processing
grass = "0.13.4"
codemap = "0.1.3"

# Js minification - Updated to latest swc versions for serde compatibility
# Root dependencies
swc_bundler = { version = "31.0.0", default-features = false }
swc_common = { version = "14.0.4", features = [
    "tty-emitter",
], default-features = false }
swc_ecma_ast = { version = "15.0.0", default-features = false }
swc_ecma_codegen = { version = "17.0.2", default-features = false }
swc_ecma_loader = { version = "14.0.0", features = [
    "cache",
    "node",
], default-features = false }
swc_ecma_minifier = { version = "32.0.6", default-features = false }
swc_ecma_parser = { version = "24.0.1", default-features = false }
swc_ecma_transforms_base = { version = "26.0.1", default-features = false }
swc_ecma_visit = { version = "15.0.0", default-features = false }

# Updated swc ecosystem dependencies
swc_allocator = { version = "4.0.1" }
swc_atoms = { version = "7.0.0" }
swc_config = { version = "3.1.2" }
swc_config_macro = { version = "1.0.1" }
swc_ecma_codegen_macros = { version = "2.0.2" }
swc_ecma_lexer = { version = "23.0.1" }
swc_ecma_transforms_optimization = { version = "28.0.0" }
swc_ecma_usage_analyzer = { version = "22.0.1" }
swc_ecma_utils = { version = "21.0.0" }
swc_eq_ignore_macros = { version = "1.0.1" }
swc_graph_analyzer = { version = "14.0.1" }
swc_macros_common = { version = "1.0.1" }
swc_sourcemap = { version = "9.3.4" }
swc_timer = { version = "1.0.0" }
swc_visit = { version = "2.0.1" }
browserslist-rs = { version = "0.19.0" }

[build-dependencies]
built = { version = "0.8.0", features = ["git2"] }
