[package]
name = "dioxus-hooks"
version = "0.7.0-alpha.2"
authors = ["Jonathan Kelley"]
edition = "2024"
resolver = "3"
description = "Basic useful hooks for Dioxus."
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react"]

[features]
default = []
nightly-features = []

[dependencies]
dioxus-core = { path = "../core" }
dioxus-signals = { path = "../signals" }
futures-channel = "0.3.31"
tracing = "0.1.41"
slab = "0.4.11"
futures-util = "0.3.31"
generational-box = { path = "../generational-box" }
rustversion = "1.0.22"
warnings = "0.2.1"

[dev-dependencies]
futures-util = { version = "0.3.31", default-features = false }
dioxus-core = { path = "../core" }
dioxus = { path = "../dioxus" }
web-sys = { version = "0.3.80", features = ["Document", "Window", "Element"] }
tokio = { version = "1.47.1", features = ["full"] }
reqwest = { path = "../../../reqwest" }

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
