[package]
name = "subsecond-types"
version = "0.7.0-alpha.2"
edition = "2024"
resolver = "3"
authors = ["Jonathan Kelley"]
description = "Types crate for the Subsecond hotpatch engine."
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
keywords = ["hotpatch", "engine", "subsecond", "dioxus"]


[dependencies]
serde = { version = "1.0.226", features = ["derive"] }
