[package]
name = "dioxus-autofmt"
version = "0.7.0-alpha.2"
edition = "2024"
resolver = "3"
authors = ["Jonathan Kelley"]
description = "Autofomatter for Dioxus RSX"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["web", "desktop", "mobile", "gui", "wasm"]

[dependencies]
dioxus-rsx = { path = "../rsx" }
proc-macro2 = { version = "1.0.101", features = ["span-locations"] }
quote = "1.0.40"
syn = { version = "2.0.106", features = [
    "full",
    "extra-traits",
    "visit",
    "visit-mut",
] }
serde = { version = "1.0.226", features = ["derive"] }
prettyplease = "0.2.37"
regex = "1.11.2"

[dev-dependencies]
pretty_assertions = "1.4.1"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
