[package]
name = "dioxus-fullstack-hooks"
authors = ["Jonathan Kelley", "Evan Almloff"]
version = "0.7.0-alpha.2"
edition = "2024"
description = "Hooks for serializing futures, values in dioxus-fullstack and other utilities"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["web", "gui", "server"]
resolver = "3"

[dependencies]
dioxus-core = { path = "../core" }
dioxus-signals = { path = "../signals" }
dioxus-hooks = { path = "../hooks" }
dioxus-fullstack-protocol = { path = "../fullstack-protocol" }
futures-channel = "0.3.31"
serde = "1.0.226"
dioxus-history = { path = "../history" }

[dev-dependencies]
dioxus-fullstack = { path = "../fullstack" }
dioxus = { path = "../dioxus", features = ["fullstack"] }

[features]
web = []
server = []

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
