[package]
name = "manganis-core"
edition = "2024"
version = "0.7.0-alpha.2"
resolver = "3"
authors = ["Jonathan Kelley"]
description = "core for manganis"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "assets"]


# be careful with dependencies you add here - these need to get compiled for the proc macro and therefore
# prevent the main code from compiling!
[dependencies]
serde = { version = "1.0.226", features = ["derive"] }
const-serialize = { path = "../../const-serialize", features = ["serde"] }
dioxus-core-types = { path = "../../core-types", optional = true }
dioxus-cli-config = { path = "../../cli-config", optional = true }

[dev-dependencies]
manganis = { path = "../manganis" }
dioxus = { path = "../../dioxus" }

[features]
dioxus = ["dep:dioxus-core-types", "dep:dioxus-cli-config"]
