[package]
name = "dioxus-config-macros"
edition = "2024"
resolver = "3"
version = "0.7.0-alpha.2"
authors = ["Dioxus Labs"]
description = "Macros used internally by codegen"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["web", "desktop", "mobile", "gui", "wasm"]

[dependencies]

[features]
default = []
wasm-split = []
