[package]
name = "dioxus-asset-resolver"
edition = "2024"
resolver = "3"
version = "0.7.0-alpha.2"
authors = ["Jonathan Kelley", "Dioxus Labs"]
description = "Cross-platform asset resolver for manganis and dioxus"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["web", "desktop", "mobile", "gui", "wasm"]

[dependencies]
http = "1.3.1"
percent-encoding = "2.3.2"
infer = "0.19.0"
thiserror = "2.0.16"
dioxus-cli-config = { path = "../cli-config" }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21.1"
ndk = { version = "0.9.0" }
ndk-sys = { version = "0.6.0" }
ndk-context = { version = "0.1.1" }
