[package]
name = "dioxus-server"
authors = ["Jonathan Kelley", "Evan Almloff"]
version = "0.7.0-alpha.2"
edition = "2024"
description = "Fullstack utilities for Dioxus: Build fullstack web, desktop, and mobile apps with a single codebase."
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["web", "desktop", "mobile", "gui", "server"]
resolver = "3"

[dependencies]
# dioxus
dioxus-core = { path = "../core" }
dioxus-core-macro = { path = "../core-macro" }
dioxus-signals = { path = "../signals" }
dioxus-document = { path = "../document" }
dioxus-html = { path = "../html" }
generational-box = { path = "../generational-box" }

# server functions
server_fn = { version = "0.8.7", default-features = false }

# axum + native deps
axum = { version = "0.8.4", default-features = false }
tower-http = { version = "0.6.6", features = ["fs"], optional = true }
tokio-util = { version = "0.7.16", features = ["rt"], optional = true }
tokio-stream = { version = "0.1.17", features = ["sync"], optional = true }
tower = { version = "0.5.2", features = ["util"], optional = true }
tower-layer = { version = "0.3.3", optional = true }
hyper-util = { version = "0.1.17", features = ["full"], optional = true }
hyper = { version = "1.7.0", optional = true }
http = "1.3.1"

# Dioxus + SSR
dioxus-ssr = { path = "../ssr" }
dioxus-isrg = { path = "../isrg" }
dioxus-router = { path = "../router", features = ["streaming"] }
dioxus-fullstack-hooks = { path = "../fullstack-hooks" }
dioxus-fullstack-protocol = { path = "../fullstack-protocol" }
dioxus-interpreter-js = { path = "../interpreter", optional = true }

tracing = "0.1.41"
tracing-futures = "0.2.5"
async-trait = "0.1.89"
serde = "1.0.226"
enumset = "1.1.10"

futures-util = "0.3.31"
futures-channel = "0.3.31"
ciborium = "0.2.2"
base64 = "0.22.1"
rustls = { version = "0.23.32", optional = true }
hyper-rustls = { version = "0.27.7", optional = true }

pin-project = { version = "1.1.10" }
thiserror = "2.0.16"
bytes = "1.10.1"
parking_lot = { version = "0.12.4", features = ["send_guard"] }
web-sys = { version = "0.3.80", features = [
    "Window",
    "Document",
    "Element",
    "HtmlDocument",
    "Storage",
    "console",
] }

dioxus-cli-config = { path = "../cli-config" }
dioxus-devtools = { path = "../devtools", optional = true }
aws-lc-rs = { version = "1.14.0", optional = true }
dioxus-history = { path = "../history" }
subsecond = { path = "../subsecond/subsecond" }
inventory = "0.3.21"
dashmap = "7.0.0-rc2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1.47.1", features = ["rt", "sync", "macros"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.47.1", features = ["rt", "sync", "rt-multi-thread", "macros", "net"] }

[dev-dependencies]
dioxus = { path = "../dioxus", features = ["fullstack"] }

[features]
default = ["devtools", "full"]
full = [
    "core",
    "server_fn/ssr",
    "dep:tower-http",
    "default-tls",
    "dep:tower",
    "dep:hyper",
    "dep:tower-layer",
    "dep:tokio-util",
    "dep:hyper-util",
    "axum/default",
]
core = [
    "server_fn/axum-no-default",
    "server_fn/ssr",
    "document",
]
devtools = ["dep:dioxus-devtools"]
document = ["dep:dioxus-interpreter-js"]
default-tls = ["server_fn/default-tls"]
rustls = ["server_fn/rustls", "dep:rustls", "dep:hyper-rustls"]
aws-lc-rs = ["dep:aws-lc-rs"]

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
features = ["axum", "web", "aws-lc-rs"]
