[package]
name = "dioxus-config-macro"
version = "0.7.0-alpha.2"
authors = ["Jonathan Kelley"]
edition = "2024"
resolver = "3"
description = "Configuration macros for Dioxus"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["web", "desktop", "mobile", "gui", "wasm"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.101"
quote = "1.0.40"

[features]
default = []
fullstack = []
desktop = []
mobile = []
web = []
ssr = []
liveview = []

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
