[package]
name = "lazy-js-bundle"
version = "0.7.0-alpha.2"
edition = "2024"
resolver = "3"
authors = ["Jonathan Kelley"]
description = "A codegen library to bundle TypeScript into JavaScript without requiring a bundler to be installed"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
documentation = "https://docs.rs/dioxus"
keywords = ["ts", "codegen", "typescript", "javascript", "wasm"]
