[package]
name = "dioxus-devtools"
authors = ["Jonathan Kelley", "Evan Almloff"]
version = "0.7.0-alpha.2"
edition = "2024"
resolver = "3"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com/learn/0.4/migration/hot_reload"
description = "Hot reloading utilities for Dioxus"
keywords = ["dom", "ui", "gui", "react", "hot-reloading"]

[dependencies]
dioxus-signals = { path = "../signals" }
dioxus-core = { path = "../core", features = ["serialize"] }
dioxus-devtools-types = { path = "../devtools-types" }
dioxus-cli-config = { path = "../cli-config" }
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
subsecond = { path = "../subsecond/subsecond" }
thiserror = "2.0.16"

# hot reloading serve
tracing = "0.1.41"
warnings = "0.2.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tungstenite = "0.27.0"

[dev-dependencies]
tokio = { version = "1.47.1", features = ["full"] }
serde_json = "1.0.145"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
