[package]
name = "fullstack-hackernews-example"
version = "0.1.0"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
edition = "2024"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { path = "../../packages/dioxus", features = ["fullstack", "router"] }
chrono = { version = "0.4.42", features = ["serde"] }
reqwest = { path = "../../../reqwest", features = ["json"] }
serde = { version = "1.0.226", features = ["derive"] }

[features]
default = []
server = ["dioxus/server"]
web = ["dioxus/web"]
