[package]
name = "dioxus-router-macro"
version = "0.7.0-alpha.2"
authors = ["Evan Almloff"]
edition = "2024"
resolver = "3"
description = "Macro for Dioxus Router"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
documentation = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react", "router"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.106", features = ["extra-traits", "full"] }
quote = "1.0.40"
proc-macro2 = "1.0.101"
slab = "0.4.11"
base16 = "0.2.1"
digest = "0.11.0-rc.2"
sha2 = "0.11.0-rc.2"

[dev-dependencies]
dioxus = { path = "../dioxus", features = ["router"] }

[features]
default = []
web = [] #todo(jon) remove this before releasing 0.7!

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
