[package]
name = "dioxus-rsx"
version = "0.7.0-alpha.2"
authors = ["Jonathan Kelley", "Evan Almloff"]
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Core functionality for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
documentation = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = { version = "1.0.101", features = ["span-locations"] }
proc-macro2-diagnostics = "0.10.1"
quote = "1.0.40"
syn = { version = "2.0.106", features = ["full", "extra-traits", "visit", "visit-mut"] }

[features]
default = []

[dev-dependencies]
prettyplease = "0.2.37"
prettier-please = { version = "0.3.0", features = ["verbatim"] }

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
